// Downloads the webfonts this site uses and writes a local @font-face sheet,
// so no request goes to Google when someone opens a page.
//
//   node tools/fetch-fonts.mjs
//
// Re-run only to change weights or pick up a font revision. The output
// (assets/fonts/ and css/fonts.css) is committed, so a normal build needs
// nothing and the site stays a pile of static files.

import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'assets', 'fonts');

const SPEC = 'family=Archivo:wght@400;600;700'
  + '&family=IBM+Plex+Mono:wght@400;500'
  + '&family=IBM+Plex+Sans:wght@400;500;600';

// Only the ranges this site's text actually needs. Latin-ext covers the
// accents in "résumé"; the Cyrillic, Greek and Vietnamese subsets Google
// also serves would be dead weight.
const WANTED_SUBSETS = ['latin', 'latin-ext'];

// A modern UA, otherwise Google serves ttf instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

const css = await (await fetch(`https://fonts.googleapis.com/css2?${SPEC}&display=swap`, {
  headers: { 'User-Agent': UA },
})).text();

// Google labels each @font-face block with a /* subset */ comment above it.
const blocks = [];
const re = /\/\*\s*([\w-\[\]]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g;
let m;
while ((m = re.exec(css)) !== null) blocks.push({ subset: m[1], block: m[2] });

mkdirSync(outDir, { recursive: true });

const kept = [];
let bytes = 0;

for (const { subset, block } of blocks) {
  if (!WANTED_SUBSETS.includes(subset)) continue;

  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
  if (!family || !weight || !url) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`;
  const data = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(join(outDir, file), data);
  bytes += data.length;
  console.log(`  ${(data.length / 1024).toFixed(1).padStart(6)} KB  ${file}`);

  kept.push({ family, weight, style, file, range });
}

const sheet = `/* Generated by tools/fetch-fonts.mjs. Do not edit by hand.
   Self-hosted so that opening a page sends no request to Google.
   Archivo and IBM Plex are both under the SIL Open Font License 1.1;
   see assets/fonts/README.txt. */

${kept.map(f => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('../assets/fonts/${f.file}') format('woff2');${f.range ? `
  unicode-range: ${f.range};` : ''}
}`).join('\n\n')}
`;

writeFileSync(join(root, 'css', 'fonts.css'), sheet);

writeFileSync(join(outDir, 'README.txt'),
  `Fonts used by this site, self-hosted so that no request goes to a third party.

Archivo
  Copyright (c) Omnibus-Type
  SIL Open Font License 1.1
  https://fonts.google.com/specimen/Archivo

IBM Plex Sans and IBM Plex Mono
  Copyright (c) IBM Corp.
  SIL Open Font License 1.1
  https://github.com/IBM/plex

The SIL Open Font License 1.1 is at https://openfontlicense.org.
Files here were fetched by tools/fetch-fonts.mjs and are unmodified.
`);

console.log(`\n${kept.length} files, ${(bytes / 1024).toFixed(0)} KB total`);
console.log('wrote css/fonts.css and assets/fonts/README.txt');
